runtime: nodejs18
env: standard
entrypoint: npm start

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

env_variables:
  INSTANCE_CONNECTION_NAME: "amplified-coder-407814:asia-southeast2:advokata-db"
  DB_USER: "rifal"
  DB_PASS: "1234"
  DB_NAME: "advokataDB"
  JWT_SECRET: "vPEqXpiZkmiMCYqeCbWagygFLqQTnuzKzxFTTULEJKqiMLqpwCazBxPtyYeYAXjDpQJgZdkBWMmZYRSbHbLFZietKrewefpcLvVU"
  NODE_ENV: "production"
