steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build your application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Deploy to App Engine (contoh untuk App Engine)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'app'
      - 'deploy'

options:
  logging: CLOUD_LOGGING_ONLY  # Mengarahkan log hanya ke Cloud Logging

# Service account used for Cloud Build
serviceAccount: 'your-service-account@your-project.iam.gserviceaccount.com'
